flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location:
    git: https://github.com/theNerd247/blaze-bootstrap.git
    commit: a4bea1a841bca77c00e8e0c65092330586211e7b
extra-deps: []
resolver: lts-8.8
system-ghc: false
docker:
  enable: false
  container-name: "ariaracer"
image: 
  containers: 
    - name: "ariaracer"
      base: "fpco/stack-run"
      add:
        scripts/: /usr/share/ariaracer/scripts
        js/: /usr/share/ariaracer/js
        css/: /usr/share/ariaracer/css
        fonts/: /usr/share/ariaracer/fonts
